### ISSUE TITLE
Total amount of resources is not preserved during transfer

### ISSUE THREAD

**Issue by Vladimir-csp** [PapaJoesSoup/ShipManifest#36] opened 2017-03-09 09:33 UTC
Here is an example of 12% increase of LF+OX after transfer between two ships (multiple different tanks on both). http://imgur.com/a/5UfzN

**Comment by PapaJoesSoup** [comment] 2017-04-29 21:47
Is the vessel transfer mode enabled?  Or, are you simply selecting multiple parts in the source and destination?

**Comment by Vladimir-csp** [comment] 2017-04-30 03:50
Both ways.

**Comment by PapaJoesSoup** [comment] 2017-04-30 04:22
Thanks.  Looking at that section of code now.

**Comment by PapaJoesSoup** [comment] 2017-05-22 07:16
Think I have this licked.  I've not been able to reproduce since my fixes.  We will see.  Fix will be included in 5.1.4.0

**Closed by PapaJoesSoup** 2017-05-22 07:16 UTC
Labels: bug

**Comment by Vladimir-csp** [comment] 2017-09-01 18:44
Unfortunately, I'm still seeing this with 5.2.0.
Transfering from one Jumbo to 4xFL-T400, I get extra fuel. Transfering back reduces to amount a bit less than before starting point.
